version: "3.8"

services:
  keycloak_db:
    container_name: keycloak_db
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8484:8080"
    depends_on:
      - keycloak_db
  keycloak-config-cli:
    image: docker.io/adorsys/keycloak-config-cli:latest-16.1.0
    container_name: keycloak-config-cli
    depends_on:
      - keycloak
    environment:
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      IMPORT_VARSUBSTITUTION: 'true'
      IMPORT_PATH: /keycloak-config.json
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: 'true'
      IMPORT_FORCE: 'true'
    volumes:
      - ./keycloak-config.json:/keycloak-config.json
